### ISSUE TITLE
How to Mirror Images to Disconnected ARO

### ISSUE THREAD

**Issue by jflowers** [redhat-cop/ocp-disconnected-docs#20]
Create a doc to detail how to mirror images in a disconnected ARO cluster.

Plain Old Images Examples:

registry.redhat.io/rhel8/python-38
registry.access.redhat.com/ubi8/openjdk-8

**Comment by theckang** [comment]
The official endpoints list provided by Azure opens `registry.redhat.io` and `registry.access.redhat.com`

As a result, you won't need to mirror images manually.

**Comment by jflowers** [comment]
Are there other registries that are open? Like docker and/or quay? What are all the registries the cluster can pull from when disconnected?

**Comment by theckang** [comment]
- quay.io
- registry.redhat.io
- mirror.openshift.com
- arosvc.azurecr.io (internal private registry for ARO operatos)

**Comment by theckang** [comment]
Oops, yep good point.  I thought this was specific to red hat registries.  Let me unlink the PR.

**Comment by arvin-a** [comment]
This is addressed by ImageContentSourcePolicy pointing to your own registry.

**Comment by arvin-a** [comment]
closed.
